CREATE TABLE `user` (
  `user_id` varchar(32) NOT NULL COMMENT '主键，用户id',
  `user_code` varchar(50) DEFAULT NULL,
  `user_type` varchar(5) DEFAULT NULL COMMENT '用户类型',
  `name` varchar(50) DEFAULT NULL COMMENT '姓名',
  `birthday` datetime DEFAULT NULL COMMENT '生日',
  `phone` varchar(20) DEFAULT NULL COMMENT '电话',
  `mobile` varchar(20) DEFAULT NULL COMMENT '手机',
  `address` varchar(200) DEFAULT NULL COMMENT '地址',
  `sex` varchar(1) DEFAULT NULL COMMENT '性别',
  `dept_name` varchar(32) DEFAULT NULL COMMENT '部门名称',
  `dept_id` varchar(32) DEFAULT NULL COMMENT '部门id',
  `role_id` varchar(32) DEFAULT NULL COMMENT '角色id',
  `role_name` varchar(50) DEFAULT NULL COMMENT '角色名称',
  `user_status` varchar(1) DEFAULT NULL COMMENT '1:在职，2:离职，3:停职，4：其他',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `create_id` varchar(32) DEFAULT NULL COMMENT '创建人id',
  `create_name` varchar(50) DEFAULT NULL COMMENT '创建人姓名',
  `update_id` varchar(32) DEFAULT NULL COMMENT '更新人id',
  `update_name` varchar(32) DEFAULT NULL COMMENT '更新人姓名',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `status` varchar(5) DEFAULT NULL,
  `udf_1` varchar(100) DEFAULT NULL,
  `udf_2` varchar(100) DEFAULT NULL,
  `udf_3` varchar(100) DEFAULT NULL,
  `udf_4` varchar(100) DEFAULT NULL,
  `udf_5` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8